### ISSUE TITLE
Dropdown Server Side - invalid selection bug

### ISSUE THREAD

**Issue by tlrib** [OutSystems/outsystems-ui#1001]
Hey guys,

Found a bug in the DropdownServerSide pattern.
When I deselect an option, the grey background (that means that the option is selected) does not go away by itself. Only after clicking somewhere else it disappears.
This only happens on mobile, please see the video:

https://github.com/user-attachments/assets/fe31b3d4-85c7-4279-b5b8-7be1ce755d9b

I'm quite sure the issue is because of the following hover selector:

![image](https://github.com/user-attachments/assets/8a2efe30-3d5b-4a9e-bf67-ffdfd2715d9c)

This is fixable with CSS only by just setting the .osui-dropdown-serverside-item--is-selected with higher priority than the hover one.
I have this fixed on my side, but as this probably impacts more users it would be nice if it can get fixed in the outsystemsUI side.

[Here's a link for the .oml file if you want a quick reproduction](https://file.io/OTkktMOzVnDA)

Additionaly, the name and description of the parameter "IsSelected" of the DropdownServerSideItem block make no sense, since they don't match the functionality. It brought me a lot of confusion when I first started using this pattern. If you could fix that as well it would be great :)

![image](https://github.com/user-attachments/assets/01eca161-c720-41c7-bb23-d9158035efd2)

Thanks,
Best regards,
Tiago

**Comment by joselrio** [comment]
Hi @tlrib,

First of all, thank you for the feedback!

Once DropdownServerSide have the **AllowMultipleSelection=True**, the **IsSelected** attribute should be managed by the OutSystems Developer once a click occurs at a **DropdownServerSideItem**.
That is an input that will/should be assigned through a flag value based on the data-base/structure values intent logic...

When for instance, DropdownServerSide has the **AllowMultipleSelection=False**, once any **DropdownServerSideItem** is clicked it will immediately close, that is the difference between this attribute values.
Off course at this context the **DropdownServerSide > IsSelected** attribute is/should be managed by the implementation logic as well, despite the selected state is being also added in the first click moment though JS as well.

Also, over color is darker that the selected one (unless you have custom styling), take a look at the image below:
<img width="346" alt="Screenshot 2024-11-07 at 12 03 40" src="https://github.com/user-attachments/assets/78864b0d-fed3-43c7-87e6-111f28240460">

The **IsSelected** attribute description is indeed wrong!

Again, thank you for the feedback!
Let us know if you have any doubt or suggestion...

Meanwhile we will take care of that attribute description change.

Cheers,
JR
