### ISSUE TITLE
Animated Label - when content is removed programmatically, it doesn't behave as expected

### ISSUE THREAD

**Issue by jfranco09** [OutSystems/outsystems-ui#760]
When I'm using the animated label pattern, it's not behaving as expected in the following scenario:

1. Animated Label Pattern has already data loaded
2. Change a different input, which triggers a client screen action
3. Said action removed programmatically the animated label data

Expected behavior: The label should merge into the input
Actual behavior: The label stays as if it had still data. After clicking outside the animated label, it triggers other event which is working properly

![Screen1 - 19 June 2023](https://github.com/OutSystems/outsystems-ui/assets/11746338/1c6f760d-cad1-49f5-8dde-dd5577e9b262)

Possible root cause:

The default value should be false instead of undefined, because the function isn't handling the undefined case.

https://github.com/OutSystems/outsystems-ui/blob/7cc14100a29c8f8d15e0c4fc444fe1a8a7833547/src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts#L63

Other possible fix would be to pass false in both cases, but it wouldn't prevent for future bugs like this.
https://github.com/OutSystems/outsystems-ui/blob/7cc14100a29c8f8d15e0c4fc444fe1a8a7833547/src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts#L130

https://github.com/OutSystems/outsystems-ui/blob/7cc14100a29c8f8d15e0c4fc444fe1a8a7833547/src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts#L207

**Comment by gnbm** [comment]
Hi @jfranco09 
Thanks for reaching out and for the context.
Could you please just include a GIF/Video of the reported behaviour just to make sure it's the same scenario we'll check?
Thank you in advance.

Cheers,
GM

**Comment by jfranco09** [comment]
Hi @gnbm 
I updated the  issue with the GIF. I also tried to solve this by creating a pull request but I'm facing some issues because it's the first time I contribute, and I currently suck at it.

**Comment by joselrio** [comment]
Thank you for your contribution @jfranco09!
