### ISSUE TITLE
Submenu widget does not use header colors

### ISSUE THREAD

**Issue by Mafti** [OutSystems/outsystems-ui#842]
The submenu is mostly uses as part of the topmenu, which is part of the header.
Now If I have a header in a different contrast I need knowledge of the pattern and its styles to fix it.
I can agree with the underlin to behave like the primary color.
But the font-color (and icon) should inherit the colors of the parent containers, by all menas never use explicit color-neutral-9

now I have these in my CSS, which should not be necessary.

.desktop .osui-submenu:hover .osui-submenu__header__item,
.desktop .osui-submenu__header__item{
    color: var(--color-neutral-0)
}
.desktop .osui-submenu:hover .osui-submenu__header__icon:before,
.desktop .osui-submenu__header__icon:before {
  border-color: var(--color-neutral-0)
}

**Comment by BenOsodrac** [comment]
Hi @Mafti,

I understand your point, but the Submenu pattern was built to work independently, event outside of the Header or Menu Blocks. 

As such, it's preferable to have default styles for those elements!

Also, changing styling defaults like these could result in visual breaking-changes for customers.
