### ISSUE TITLE
MenuSubItem Css active class always removed after click event is processed

### ISSUE THREAD

**Issue by thekingofspain** [OutSystems/outsystems-ui#896]
I have a MenuSubItem that is progamically set to **active**.  However when the active MenuSubItem is clicked, the **active** class is removed.  The removal of the class occurs after the active sub menu's link click event is handled on the client side.  Calling the _SetActiveMenuItems_ or custom js code in the active sub menu's link click event handler indicates that the MenuSubItem is still active at the time the event handler is executed.

**Comment by gnbm** [comment]
@thekingofspain could you please share a sample where that can be reproduced? Thank you
